//! Simple validator example demonstrating the ELO Rust target vision
//!
//! This example shows how ELO expressions compile to zero-cost Rust validators.
//! In production, this would be generated from an ELO rule:
//!
//! ```elo
//! email matches "^[a-z]+@example\.com$" &&
//! age >= 18 &&
//! verified == true
//! ```

use std::fmt;

/// A sample user type
#[derive(Debug, Clone)]
struct User {
    email: String,
    age: i32,
    verified: bool,
}

/// Validation error
#[derive(Debug, Clone, PartialEq, Eq)]
struct ValidationError {
    path: String,
    message: String,
}

impl fmt::Display for ValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}: {}", self.path, self.message)
    }
}

/// This would be GENERATED by the ELO Rust target
/// In the real implementation, the #[elo_validator] macro would generate this
fn validate_user(user: &User) -> Result<(), Vec<ValidationError>> {
    let mut errors = Vec::new();

    // Email validation (would use: email matches pattern)
    let email_valid = user.email.ends_with("@example.com") && user.email.len() > 11;
    if !email_valid {
        errors.push(ValidationError {
            path: "email".to_string(),
            message: "Email must be at example.com".to_string(),
        });
    }

    // Age validation (would use: age >= 18)
    if user.age < 18 {
        errors.push(ValidationError {
            path: "age".to_string(),
            message: "User must be at least 18 years old".to_string(),
        });
    }

    // Verified validation (would use: verified == true)
    if !user.verified {
        errors.push(ValidationError {
            path: "verified".to_string(),
            message: "User must be verified".to_string(),
        });
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

fn main() {
    println!("=== ELO Rust Target: Simple Validator Example ===\n");

    // Example 1: Valid user
    let valid_user = User {
        email: "john@example.com".to_string(),
        age: 25,
        verified: true,
    };

    println!("Validating: {:?}", valid_user);
    match validate_user(&valid_user) {
        Ok(()) => println!("✅ Validation passed\n"),
        Err(errs) => {
            for err in errs {
                println!("❌ {}", err);
            }
            println!();
        }
    }

    // Example 2: Invalid email
    let invalid_email = User {
        email: "john@gmail.com".to_string(),
        age: 25,
        verified: true,
    };

    println!("Validating: {:?}", invalid_email);
    match validate_user(&invalid_email) {
        Ok(()) => println!("✅ Validation passed\n"),
        Err(errs) => {
            for err in errs {
                println!("❌ {}", err);
            }
            println!();
        }
    }

    // Example 3: Underage user
    let underage = User {
        email: "jane@example.com".to_string(),
        age: 16,
        verified: true,
    };

    println!("Validating: {:?}", underage);
    match validate_user(&underage) {
        Ok(()) => println!("✅ Validation passed\n"),
        Err(errs) => {
            for err in errs {
                println!("❌ {}", err);
            }
            println!();
        }
    }

    // Example 4: Multiple errors
    let invalid_user = User {
        email: "bob@gmail.com".to_string(),
        age: 15,
        verified: false,
    };

    println!("Validating: {:?}", invalid_user);
    match validate_user(&invalid_user) {
        Ok(()) => println!("✅ Validation passed\n"),
        Err(errs) => {
            println!("❌ Multiple validation errors:");
            for err in errs {
                println!("   - {}", err);
            }
            println!();
        }
    }

    println!("=== How This Relates to ELO ===\n");
    println!("Instead of writing this validator manually, with the ELO Rust target you would:");
    println!();
    println!("  #[elo_validator(elo = r#\"");
    println!("    email matches pattern &&");
    println!("    age >= 18 &&");
    println!("    verified == true");
    println!("  \")]");
    println!("  pub struct UserValidator;");
    println!();
    println!("The ELO Rust target would generate this exact code automatically!");
    println!("Zero runtime overhead, full type safety, idiomatic Rust.");
}
